# Generated by Django 3.0.3 on 2020-03-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0009_auto_20200329_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='telefono',
            field=models.DecimalField(decimal_places=0, default='0999999', max_digits=15),
        ),
    ]
