# Generated by Django 3.0.3 on 2020-04-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
