# Generated by Django 3.0.3 on 2020-03-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0006_auto_20200329_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='barrio',
            field=models.CharField(choices=[('AG', 'Aguada'), ('BS', 'Barrio Sur'), ('BU', 'Buceo'), ('CS', 'Carrasco'), ('CT', 'Centro'), ('CE', 'Cerro'), ('CV', 'Ciudad Vieja'), ('CN', 'Cordón'), ('CR', 'Capurro'), ('LU', 'La Unión'), ('MÑ', 'Maroñas'), ('PR', 'Parque Rodó'), ('PÑ', 'Peñarol'), ('PC', 'Pocitos'), ('PG', 'Punta Gorda'), ('OT', 'Pocitos')], default='O', max_length=2),
        ),
    ]
