# Generated by Django 3.0.3 on 2020-03-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0009_auto_20200329_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamiento',
            name='is_sponsored',
            field=models.BooleanField(default=False),
        ),
    ]
