# Generated by Django 3.0.3 on 2020-04-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0010_alojamiento_is_sponsored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='titulo',
            field=models.CharField(max_length=45),
        ),
    ]
