# Generated by Django 3.0.3 on 2020-04-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0011_auto_20200401_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alojamiento',
            name='is_sponsored',
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='image',
            field=models.ImageField(default='gallery/static/images/default.jpg', upload_to='gallery'),
        ),
    ]
