# Generated by Django 3.0.3 on 2020-04-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0013_alojamiento_is_sponsored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='image',
            field=models.ImageField(default='gallery/static/images/default.png', upload_to='gallery'),
        ),
    ]
